name: payment_verifier
description: "T's Pay — Ethiopian Payment Verification & Multi-Wallet Reconciliation Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.6.2

  # Backend
  supabase_flutter: ^2.8.3

  # Fonts & Icons
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # Image
  image_picker: ^1.2.2
  cached_network_image: ^3.4.1

  # OCR
  google_mlkit_text_recognition: ^0.14.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  equatable: ^2.0.7

  # Charts
  fl_chart: ^0.69.0

  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.4

  # Environment
  flutter_dotenv: ^5.2.1

  # Animations
  lottie: ^3.3.1

  # Connectivity
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.6
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/T_s_verify_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - .env
