"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";

const DEFAULT_PRIVACY = `PRIVACY POLICY

Last Updated: July 2026

T's Verify ("we," "us," or "our") operates the T's Verify mobile application and web platform (collectively, the "Service"). This Privacy Policy informs you of our policies regarding the collection, use, disclosure, and protection of personal information when you use our Service.

By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with this policy, please do not use the Service.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Definitions

1.1 "Personal Data" means any information relating to an identified or identifiable natural person.
1.2 "Service" refers to the T's Verify mobile application and web-based administrative portal.
1.3 "Usage Data" refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
1.4 "Merchant" refers to a business entity registered on the Platform.
1.5 "User" refers to any individual accessing or using the Service.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. Information We Collect

We collect several types of information for various purposes to provide and improve our Service to you.

2.1 Personal Account Information
  - Full name
  - Email address
  - Phone number
  - Business name and business registration details
  - Business address
  - Bank account information (for settlement processing)

2.2 Transaction Data
  - Payment amounts and currencies
  - Transaction references and identifiers
  - Receipt images and OCR-processed data
  - Transaction timestamps and status information
  - Bank account numbers (partial, for verification purposes)
  - Settlement records and payout history

2.3 Usage Data
  - Device type and operating system
  - Mobile device identifiers
  - IP address
  - Browser type and version
  - Pages and features accessed
  - Time and date of visits
  - Time spent on pages
  - In-app interaction data

2.4 Authentication Data
  - Login credentials (securely hashed)
  - Session tokens
  - Login timestamps and IP addresses
  - Password reset requests

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

3. How We Use Your Information

We use the collected information for the following purposes:

3.1 To Provide and Maintain the Service
  - Processing and verifying transactions
  - Matching receipts with transaction records using OCR technology
  - Facilitating settlement processing with banking partners
  - Managing user accounts, roles, and permissions

3.2 To Improve the Service
  - Analyzing usage patterns to optimize Platform performance
  - Identifying and fixing technical issues
  - Developing new features and functionality

3.3 To Communicate With You
  - Sending transaction confirmations and notifications
  - Providing customer support and responding to inquiries
  - Sending important updates about the Service, including security notices
  - Sending administrative messages and policy change notifications

3.4 For Security and Fraud Prevention
  - Detecting and preventing fraudulent or unauthorized transactions
  - Monitoring for suspicious activity patterns
  - Conducting security audits and investigations
  - Complying with legal and regulatory obligations

3.5 For Legal Compliance
  - Maintaining records as required by Ethiopian financial regulations
  - Responding to lawful requests from regulatory authorities
  - Enforcing our Terms of Service

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. Legal Basis for Processing (GDPR Compliance)

If you are located in the European Economic Area (EEA), our legal basis for collecting and using your personal information depends on the specific data concerned and the context in which we collect it. We process your personal data:
  - To perform our contractual obligations to you.
  - With your consent, where required.
  - For our legitimate business interests, provided your rights do not override these interests.
  - To comply with legal obligations.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

5. Data Sharing and Disclosure

5.1 We Do Not Sell Your Personal Information
We do not sell, rent, or trade your personal information to third parties for marketing purposes.

5.2 We May Share Your Information With:
  - Banking Partners: To facilitate payment settlements and verify bank account details. Partners are contractually bound to protect your data.
  - Service Providers: Third-party vendors who assist in operating the Service, including cloud hosting, OCR processing, and analytics providers. These providers have access only to the information necessary to perform their functions and are bound by confidentiality agreements.
  - Regulatory Authorities: When required to comply with applicable laws, regulations, legal processes, or enforceable governmental requests.
  - Professional Advisors: Including auditors, lawyers, and accountants, where necessary for legal compliance or dispute resolution.

5.3 Business Transfers
If T's Verify is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

6. Data Security

6.1 We implement industry-standard security measures to protect your personal information, including:
  - Encryption of data in transit using TLS/SSL protocols.
  - Encryption of sensitive data at rest.
  - Role-based access controls and authentication requirements.
  - Regular security assessments and vulnerability testing.
  - Secure data center infrastructure with restricted physical access.
  - Employee training on data protection and privacy practices.

6.2 While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security. No method of electronic storage or transmission is 100% secure.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

7. Data Retention

7.1 We retain your personal data only for as long as necessary to fulfill the purposes for which it was collected, including:
  - Account data: Retained for the duration of your active account plus thirty (30) days after account deletion for processing.
  - Transaction records: Retained for a minimum of seven (7) years to comply with Ethiopian financial regulations.
  - Usage data: Retained for a period of twelve (12) months for analytics purposes.
  - Backup data: Retained in accordance with our backup and disaster recovery procedures.

7.2 When data is no longer required, it is securely deleted or anonymized.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

8. Your Rights and Choices

Depending on your jurisdiction, you may have the following rights regarding your personal data:

8.1 Right to Access: You may request a copy of the personal data we hold about you.
8.2 Right to Rectification: You may request correction of inaccurate or incomplete data.
8.3 Right to Deletion: You may request deletion of your personal data, subject to legal retention requirements.
8.4 Right to Restrict Processing: You may request that we limit the processing of your personal data under certain circumstances.
8.5 Right to Data Portability: You may request a copy of your data in a structured, machine-readable format.
8.6 Right to Object: You may object to the processing of your personal data for certain purposes.
8.7 Right to Withdraw Consent: Where processing is based on consent, you may withdraw your consent at any time.

To exercise any of these rights, please contact us at zagolinv@gmail.com. We will respond to your request within thirty (30) days.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

9. Children's Privacy

9.1 Our Service is not intended for use by individuals under the age of 18 ("Children").
9.2 We do not knowingly collect personally identifiable information from children under 18.
9.3 If we become aware that a child has provided us with personal data, we will take steps to delete that information.
9.4 If you are a parent or guardian and you believe your child has provided us with personal data, please contact us.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

10. Cookies and Tracking Technologies

10.1 The Service uses essential cookies and similar tracking technologies for the following purposes:
  - Authentication and session management
  - Security and fraud prevention
  - Maintaining user preferences

10.2 We do not use tracking cookies for advertising or marketing purposes.
10.3 You can set your browser to refuse all or some cookies, but this may affect the functionality of the Service.
10.4 For more information about the cookies we use, please contact us.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

11. International Data Transfers

11.1 Your information may be transferred to and processed on servers located outside your country of residence.
11.2 We ensure that appropriate safeguards are in place to protect your personal data in accordance with applicable data protection laws.
11.3 By using the Service, you consent to the transfer of your data to servers located in the Federal Democratic Republic of Ethiopia or other jurisdictions where our service providers operate.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

12. Changes to This Privacy Policy

12.1 We may update this Privacy Policy from time to time.
12.2 Material changes will be communicated to users via:
  - Email notification to the address associated with your account.
  - In-app notification.
  - A prominent notice on the Service at least thirty (30) days before the changes take effect.
12.3 We will update the "Last Updated" date at the top of this Privacy Policy.
12.4 Your continued use of the Service after any changes constitutes your acceptance of the updated Privacy Policy.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

13. Third-Party Services

13.1 The Service may contain links to third-party websites or services that are not owned or controlled by T's Verify.
13.2 We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.
13.3 We strongly advise you to review the privacy policy of every website or service you visit.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

14. Data Protection Officer

We have appointed a Data Protection Officer (DPO) who is responsible for overseeing questions relating to this Privacy Policy. If you have any questions, please contact our DPO:

Email: zagolinv@gmail.com
Address: Addis Ababa, Ethiopia

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

15. Complaints

15.1 If you believe that we have violated your privacy rights, please contact us immediately at zagolinv@gmail.com.
15.2 We will investigate your complaint and respond within thirty (30) days.
15.3 If you are not satisfied with our response, you have the right to lodge a complaint with the applicable data protection authority in your jurisdiction.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

16. Contact Information

If you have any questions about this Privacy Policy, please contact us:

Email: zagolinv@gmail.com
Support Email: zagolinv@gmail.com
Address: Addis Ababa, Ethiopia
Website: https://www.tsverifyapp.com/`;

export default function PrivacyPolicyPage() {
  const [darkMode, setDarkMode] = useState(() => typeof window !== "undefined" ? JSON.parse(localStorage.getItem("adminDarkMode") ?? "false") : false);
  const [content, setContent] = useState(DEFAULT_PRIVACY);

  useEffect(() => {
    const handler = (e) => setDarkMode(e.detail);
    window.addEventListener("darkmodechange", handler);
    loadContent();
    return () => window.removeEventListener("darkmodechange", handler);
  }, []);

  const loadContent = async () => {
    try {
      const { data, error } = await supabase.from("platform_settings").select("privacy_content").limit(1).maybeSingle();
      if (!error && data?.privacy_content) setContent(data.privacy_content);
    } catch { /* use default */ }
  };

  const styles = {
    bg: darkMode ? "bg-[#080E1A]" : "bg-zinc-50",
    card: darkMode ? "bg-[#0F1626]/80 border-white/[0.06]" : "bg-white/80 border-black/5 shadow-sm",
    text: darkMode ? "text-zinc-300" : "text-zinc-700",
    heading: darkMode ? "text-white" : "text-zinc-900",
    subheading: darkMode ? "text-zinc-200" : "text-zinc-800",
    blur: darkMode ? "bg-emerald-500/5" : "bg-emerald-500/3",
    headerBorder: darkMode ? "border-white/[0.06]" : "border-black/5",
  };

  return (
    <div className={`min-h-screen ${styles.bg} font-sans transition-colors duration-500`}>
      <div className={`sticky top-0 z-10 border-b backdrop-blur-xl ${styles.headerBorder} ${darkMode ? "bg-[#0F1626]/80" : "bg-white/80"}`}>
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="T's Verify" className="w-7 h-7 object-contain" />
            <span className={`text-sm font-bold ${styles.heading}`}>T's Verify</span>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/terms"
              className={`text-xs font-semibold transition-colors ${
                darkMode ? "text-zinc-400 hover:text-zinc-200" : "text-zinc-500 hover:text-zinc-800"
              }`}
            >
              Terms of Service
            </Link>
            <Link
              href="/dashboard"
              className="px-3 py-1.5 rounded-lg bg-gradient-to-r from-emerald-500 to-emerald-600 text-zinc-950 font-bold text-[10px] transition-all hover:from-emerald-400 hover:to-emerald-500"
            >
              Dashboard
            </Link>
          </div>
        </div>
      </div>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
        <div className={`relative overflow-hidden rounded-2xl border transition-all ${styles.card}`}>
          <div className={`absolute top-0 right-0 w-48 h-48 rounded-full blur-3xl pointer-events-none ${styles.blur}`} />
          <div className="p-6 sm:p-10">
            <div className={`whitespace-pre-line text-sm leading-relaxed ${styles.text}`}>
              {content.split("\n\n").map((section, i) => {
                const lines = section.split("\n");
                const isHeading = lines[0] === lines[0].toUpperCase() && lines[0].length > 3;
                if (isHeading) {
                  return (
                    <div key={i} className="mb-6">
                      <h2 className={`text-lg font-bold mb-3 ${styles.heading}`}>{lines[0]}</h2>
                      {lines.slice(1).length > 0 && (
                        <div className="space-y-2">
                          {lines.slice(1).filter(Boolean).map((line, j) => {
                            const isSubheading = /^\d+\.\d+\s/.test(line);
                            if (isSubheading) return <h3 key={j} className={`font-bold mt-3 mb-1 ${styles.subheading}`}>{line}</h3>;
                            if (line.startsWith("- ")) return <li key={j} className="ml-4 list-disc">{line.slice(2)}</li>;
                            return <p key={j}>{line}</p>;
                          })}
                        </div>
                      )}
                    </div>
                  );
                }
                return <p key={i} className="mb-4">{section}</p>;
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
